apiVersion: ENC[AES256_GCM,data:Eys=,iv:mlCXWNqHdCQ1n4EIhvvpssZPSwrD5gUhZqeN2dca0Nk=,tag:G8YM05ObWAmXTwee50z+Jg==,type:str]
kind: ENC[AES256_GCM,data:km2r/MQ/,iv:TiQAwVBEqUHQixXX20aqqSCHsT5O5tGCpA4vnuRybz4=,tag:tItCpbPggFRd1neVkYD6Rg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VWPh0RnxfYetQfgO4A==,iv:196dqdli82is5jes2uNOe1KlOPYcVRN+zRdUgZpRIjE=,tag:rYyGp7JDlVTNG8UsbnGT8A==,type:str]
    namespace: ENC[AES256_GCM,data:oY27XvULiv/uKg==,iv:4gF7uXI9Dmyl78kdVwgcgjNJuMfT5db2u62vWNF9oEs=,tag:z3Ip/8zjozH/xQ5OfTLfEw==,type:str]
type: ENC[AES256_GCM,data:s79dBoBh,iv:jD4jsmeJ38IBi3JcnhZwBNjP3BgNqWm7nNoAIl9F4/U=,tag:taXWRJFzyxqiO5WjmJAX2A==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:s4lZ6o4=,iv:7l9A6feMdIB+74KC4IN3M/ZHZmlS3ybj6nMB7427mM0=,tag:N4yZ2Nh/9FdEq6dgwUNlhw==,type:str]
    admin-password: ENC[AES256_GCM,data:fi8Wfr8Qs3etO8Z2b0pDQnsnRb9zgNxC,iv:yRSoq4Mm0iaKLc70kUMN4IfdR/Jj5SCH5yNyLtqCPJ4=,tag:CbJM05CW5bpAbdQOBvl2sg==,type:str]
sops:
    age:
        - recipient: age1245qx04gvz5rjg2mr9kmy7n95awzfvlxjgjrdsjp5xg09vx60sasr0jr7d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YlpQeXBYWXpJNnBYbHpn
            czB0WTVGbXVtMXFkV0N3QzBhZEZtbmxqVG1zCjlhMnlESTh4dWhzZEdNdTZnaXR5
            cWorOXdOZG5pY0VJNUcwa3pyYmk5RzAKLS0tIHVpb0ZqaDlxOTVzTmdwWlg3b1d5
            aTdSc1dFaElXYS9YQ2JMbXFZNFk5SjgKHUoToR/nIQNAKUA+Tbp7//rPrrotvh3X
            Fgmn59zkhJ+2ckjEKKT/Yo3HiKSxBGEdpgSma82xu2FR1PsVYKK5Hw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yc8rusaa3f7jdc90pgkqgwy4exdmudxn6drzfvz266p74w2a75as3vdzz0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5M05QUVBoYlhKdVp2YWZU
            Ni9GSFB3dlJsbkJJcklnNStTYzgxeURCQlRzCkY4SVNxWVdqdXJMaUpuRkVIMW90
            Q0I2RExhbGN1cDMrZ3ZVeEc0anlnU0kKLS0tIFFYOFNsWnVlUkU5cUpKaCs4cVdl
            K0lwdnpYRGZjR2cvUml5MXJUa1J1ZmcKjv72kTsiCcdE7UmlFxGfbBuY9XYZsgoP
            bb46SGXKOh2MlkP75ccCknN9VlB+jdifqb3/AlW1CyDNCp0t4zkoXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yhp06fu0gysk7x63xxg5re940fwjjydaynv9tnlm49v7zgxmhs7q7hq57q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVUtxL0Y2UE1IWEdJQTJr
            NTJBNTZYVFI2WVIzMjJjSWxSdUUvRkVZdmlFCk5HK1VFWEhpV2VzaEs5WVVlNUNw
            YVIvN0t2V3FDaEZFVDVsWTlKeVI5UU0KLS0tIG9WaGg2UXJNMDRRZ0NjdlZ6M0Np
            RVBSci9CYi9ub0RQT1pZdDlBVlhBcUkK3nlD9rmpjJqlgPNChWWInKvISvQCxS6A
            YG63jIcCImC3+eRBKnuJrJWZ6zV3jzY4zZ8VgzmCO58EwPz440PzJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q3anj703qwnqvw3hzcn64wgkqcyasp4t8rydfrh6huwfkdnhx5qqysgmxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUHh1ZFg5dzB2WG12WVd2
            dHl4SWFUdmwybzVlMzRVZCtrVlNnM0pWd2cwCmlmcHRTaTFSR2hKdCtseW5JVDNF
            V3lIU25Qd0VWeHZFSm4rZDJyT3ZkaTQKLS0tIERQT1dWV0hmUU82eFh0c0lQTEVK
            cW9GSnVUcVhXWVpMRkRmUE53eDl6S1kKQbXrRRWY3WnFPbc52ZpHyWRbGNW22Tqz
            I6AAXjUEQldeJeiliXHwQXeTvudPwZ/jNHp76CAbCTY8r/xjk0aGtg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ht9lynx65f80xyh5wtyl8va5x4nxrpmzm6f48epp6v6edq6k0spq0pqdnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV2hBZEwrU281Uk55RlZK
            emVQenlmNDBaZUhrOGFyeVV6cXZQaVZDM2xJClV3dGluOE55aUt2VU9rUFE3TTh0
            NWpKRlNlTXlSZWFhRnZLZlR1dGJYR1EKLS0tIGZ2UXl2SVdOQXlTNHZOVU9SV1ZW
            UGt2Q01UVDVyQkVQMVBHWGNVZVk1dDgKBw+amoKsr//qeQXjMYx8fnfg2qfBK6k2
            oZIxWJPxU2jlZrfz8xvlcDTxM3M7k9o+NysxQrekHJmWVMJv8bTlhA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age146mmq2zwlvp9x3hyf7c4adff236mkmvzqrx4gm9n78s9g4cntgmqd0d67u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbUVzcldxWjg3NkFlL2l3
            YzVzYWcvdTBTdFdPUGw2TEJyTnhuZFNIckZZCnNKM0VWODZmWTIvZEw0VVNhTjNM
            eVVGcEwrVlR1MVV4d0NMcTVkRkdZTVkKLS0tIC9BTHkrOThHenVPYWlyc2dlTEtu
            UWpmYld3WmVlRU40YWJ3U2NhdUZzS28KKemNgCENlkkdDdP1sAzLTNivbFmffWrH
            EaEMs0KbQpGnNdSfFrQlUivG16jx6A1rS6UtLuETQBbJfV9tDZC29g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rh55ur647fd784v55daarpysmqujkkyw8u7zz7lled2wlwemlcrqmaz32d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbVV4QzlZOXNWQ29hZXpH
            dnlsSXlIY1dIUXRxR2VuZE5XNldzbUtqSVg0CkxweVE2dVRxWTlTUVRKREJEV1FD
            ZTN0dnZ6cWliSkJPVjNvMHdsc1d2bFUKLS0tIHBKMmxLL3Qxc1phVUFyVnIxbGVR
            bFZveXd6NVNBRnJ2bFNIcWk0bWlXR2sKgCRprhC1LvCjrlw8CMsSORzEHSIZ1IFr
            WcVJ1rFsFGLVawYvK0f5bgqKRh909UIJNdsekH9Z3MuPtixzrR9Y0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T03:10:00Z"
    mac: ENC[AES256_GCM,data:e1dfGlGq1cycgWf5G4wB1H/L5+3IfPLIt0NvmLdehoMTBsSRrQ+B1jcRMebfHj3B10tgAeYTxrbjXhIFO5TCP8wVcB61h00IUwPY/ZriIWNd7o0l4M29BvHqDlZjmaqQ/gkdFKeM0gKHYLbaECMPxwY08K8I26ExTuT1Bd+nuY0=,iv:ZEBPmyIjDS1LiD62Kfo65/pmrgIwUFgB8D/08MrOidQ=,tag:OX1rCA8exSwoStn/z9xjIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
